const products=[
{name:'Classic Bamboo Silambam',price:499,category:'SILAMBAM',type:'stick',desc:'Balanced bamboo Â· Multiple sizes'},
{name:'Warrior Pro Silambam',price:749,category:'SILAMBAM',type:'stick',desc:'Premium selected bamboo Â· Pro training'},
{name:'Double Stick Training Set',price:799,category:'TRADITIONAL',icon:'âš”ï¸',desc:'Matched pair Â· Fast movement practice'},
{name:'Training Head Guard',price:999,category:'PROTECTION',icon:'ðŸ›¡ï¸',desc:'Protection for controlled training'},
{name:'Silambam Carry Case',price:449,category:'ACCESSORIES',icon:'ðŸŽ’',desc:'Long carry case Â· Training essential'},
{name:'Focus Training Pads',price:899,category:'ACCESSORIES',icon:'ðŸ¥Š',desc:'Speed Â· Accuracy Â· Conditioning'}];
let cart=[],filter='ALL';const $=s=>document.querySelector(s);
function renderFilters(){const cats=['ALL',...new Set(products.map(x=>x.category))];$('#filters').innerHTML=cats.map(c=>`<button class="${c===filter?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;renderFilters();renderProducts()})}
function renderProducts(){$('#products').innerHTML=products.map((p,i)=>({p,i})).filter(x=>filter==='ALL'||x.p.category===filter).map(({p,i})=>`<article class="product reveal visible"><div class="visual">${p.type==='stick'?'<div class="stick-art"></div>':`<div class="emoji">${p.icon}</div>`}</div><div class="product-body"><div class="tag">${p.category}</div><h3>${p.name}</h3><div class="desc">${p.desc}</div><div class="product-foot"><div class="price">â‚¹${p.price}</div><button class="add" data-i="${i}">+</button></div></div></article>`).join('');document.querySelectorAll('.add').forEach(b=>b.onclick=()=>{cart.push(products[+b.dataset.i]);updateCart();openCart()})}
function updateCart(){ $('#count').textContent=cart.length; $('#cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><div>${p.name}<br><small>â‚¹${p.price}</small></div><button data-r="${i}">REMOVE</button></div>`).join(''):'<p style="text-align:center;color:#766f66;margin-top:45px">Your arsenal is empty.</p>'; $('#total').textContent=cart.reduce((s,p)=>s+p.price,0);document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.r,1);updateCart()})}
function openCart(){ $('#cart').classList.add('open');$('#overlay').classList.add('show') }function closeCart(){ $('#cart').classList.remove('open');$('#overlay').classList.remove('show') }$('#bagBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;
$('#checkout').onclick=()=>{if(!cart.length)return alert('Your arsenal is empty.');let total=cart.reduce((s,p)=>s+p.price,0),msg='âš”ï¸ SAB SILAMBAM ORDER âš”ï¸\n\n'+cart.map(p=>`â€¢ ${p.name} â€” â‚¹${p.price}`).join('\n')+`\n\nTOTAL: â‚¹${total}\n\nPlease confirm availability.`;const phone='919488637786';window.open(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`,'_blank')};
function finder(){let h=$('#height').value,l=$('#level').value;if(!h||!l)return $('#result').textContent='Select your profile.';let s=h==='short'?'4 FT â€“ 5 FT':h==='medium'?'5 FT â€“ 6 FT':h==='tall'?'6 FT':'6 FT â€“ 7 FT';$('#result').innerHTML=`RECOMMENDED STARTING RANGE<br><br><b>${s}</b><br><small>${l} training</small>`}$('#height').onchange=finder;$('#level').onchange=finder;
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));
for(let i=0;i<25;i++){let s=document.createElement('i');s.className='spark';s.style.left=Math.random()*100+'vw';s.style.animationDuration=6+Math.random()*9+'s';s.style.animationDelay=Math.random()*9+'s';$('#sparks').appendChild(s)}
document.addEventListener('mousemove',e=>{if(innerWidth<850)return;let x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*6;$('.hero-bg').style.transform=`scale(1.06) translate(${x}px,${y}px)`});window.addEventListener('load',()=>setTimeout(()=>$('#loader').classList.add('hide'),700));renderFilters();renderProducts();updateCart();
